name: Pylint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      #1️⃣ Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v4

      #2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      #3️⃣ Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r "Customer-Churn-Predicion/requirements.txt"

      #4️⃣ Run Pylint (NON-BLOCKING)
      - name: Run pylint
        run: |
          pylint "Customer-Churn-Predicion/app.py" \
          --disable=import-error,missing-module-docstring,invalid-name,unused-import \
          || true
